name: Generate Metrics Release

on:
  release:
    types: [released]
  pull_request:
    types:
      - closed

jobs:
  send-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Metrics SonarCloud
        run: python3 metrics/metrics_file.py ${{ github.event.repository.name }} ${{ github.ref_name }}

      - name: Commit Metrics SonarCloud File
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_USERNAME }}"
          git clone --single-branch --branch main "https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/fga-eps-mds/2022-2-PUMA-Doc" puma_docs_repo
          mkdir -p puma_docs_repo/analytics-raw-data
          cp -R analytics-raw-data/*.json puma_docs_repo/analytics-raw-data
          cd puma_docs_repo
          git add .
          git commit -m "Gerando métricas SonarCloud - ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
          echo "Metrics File Generated Successfully."
